name: Linux Arm Workflow to deploy docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_INSTANCE_SG_ID: ${{ secrets.AWS_INSTANCE_SG_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-south-1  # Replace with your AWS region
    strategy:
      matrix:
        architecture: [arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t qaorg .

      - name : copy files to ec2
        run: rsync -avz --exclude='node_modules' --exclude='dist/logs' ./Dockerfile ${{ secrets.SSH_USERNAME }}@$${{ secrets.EC2_INSTANCE_IP }}:/home/ec2-user/workspace/organization-service/
      

      - name: Save Docker image
        run: |
          uname -m
          docker save qaorg:latest | gzip > qaorg.tar.gz
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Get runner IP address
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Whitelist runner IP address
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id ${{ secrets.AWS_INSTANCE_SG_ID }} \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32

      - name: Transfer and load Docker image
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_INSTANCE_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "qaorg.tar.gz"
          target: "/home/ec2-user/workspace/organization-service/"

      - name: SSH command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_INSTANCE_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SERVER_PASSPHRASE }}
          script: |
            cd /home/ec2-user/workspace/organization-service/
            sudo gunzip qaorg.tar.gz
            sudo docker stop qaorg || true
            sudo docker rm -f qaorg || true
            sudo docker load -i qaorg.tar
            sudo docker run --name qaorg -dp 3000:3000 qaorg:latest
            rm -rf qaorg.tar.gz
            rm -rf qaorg.tar
            
      - name: revoke runner ip address
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id $AWS_INSTANCE_SG_ID \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32
      
