name: Workingfile with ecrtag
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Select a tag to deploy'
        required: true
        options:
          - dev
          - stage
          # Add more options dynamically based on ECR repository tags

jobs:
  list_ecr_tags:
    runs-on: ubuntu-latest
    steps:
      - name: List ECR image tags
        id: list_tags
        run: |
          tags=$(aws ecr describe-images --repository-name prodagentservice --query 'imageDetails[*].[imageTags]' --output json | jq -r 'flatten | .[]')
          echo "::set-output name=tags::$tags"

  deploy_to_ec2:
    runs-on: ubuntu-latest
    needs: list_ecr_tags
    steps:
      - name: SSH into EC2 instance and deploy Docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_EC2_INSTANCE_IP }}
          username: ${{ secrets.PROD_SSH_USERNAME }}
          key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.EC2_INSTANCE_PASSPHRASE }}
          script: |
            cd /home/ec2-user/workspace/agent-service

            # Prompt the user to select a tag
            selected_tag="${{ github.event.inputs.tag }}"
            echo "Selected tag: $selected_tag"

            # Pull the selected Docker image
            docker login -u AWS -p "$(aws ecr get-login-password --region ap-southeast-1)" 589943763826.dkr.ecr.ap-southeast-1.amazonaws.com
            docker pull 589943763826.dkr.ecr.ap-southeast-1.amazonaws.com/prodagentservice:$selected_tag

            # Start the Docker container with the selected tag
            sudo docker run -d -p 3002:3002 --name agentlatest --env-file .env 589943763826.dkr.ecr.ap-southeast-1.amazonaws.com/prodagentservice:$selected_tag
